spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/concurrency
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 100
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
